services:
  sports:
    image: mysql:5.6
    ports:
      - "3317:3306"
    container_name: sports
    environment:
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin123
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: sports
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - sports_data:/var/lib/mysql
volumes:
  sports_data:
    driver: local
